services:
  # Servicio 1: La Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Servicio 2: Tu Aplicaci√≥n Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Usamos 'db' (el nombre del servicio) como host
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: